project:
  type: website
  output-dir: docs
  render:
  - "!vignettes/open-preprints.qmd"
  - "!vignettes/0001-preprint_assertions.qmd"


website:
  title: "Tales of True North"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - scripts/component/open-registrations.qmd
      #- scripts/component/open-preprints.qmd
      #- scripts/project/001-preprint_assertions.qmd
      - href: scripts/projects/los-registration-badges.qmd
        text: LOS Registration Badges

format:
  html:
    code-fold: true
    code-line-numbers: true
    code-summary: "See the code"
    code-block-border-left: true
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  warning: false
  message: false